# Generated by Django 5.1.6 on 2025-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('numero_classe', models.CharField(max_length=20)),
                ('profissao', models.CharField(max_length=20)),
            ],
        ),
    ]
