# Generated by Django 5.0.2 on 2024-07-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ponto_referencia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rua',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
