# Generated by Django 5.0.2 on 2024-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_bairro_alter_paciente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rua',
            field=models.CharField(max_length=50),
        ),
    ]
