# Generated by Django 5.0.2 on 2024-04-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome_pai', models.CharField(max_length=50)),
                ('nome_mae', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.TextField()),
                ('cep', models.CharField(max_length=20)),
                ('ponto_referencia', models.TextField()),
            ],
        ),
    ]
