# Generated by Django 5.1.6 on 2025-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.TextField(blank=True)),
                ('cep', models.CharField(max_length=20)),
                ('ponto_referencia', models.TextField(blank=True)),
                ('nome_mae', models.CharField(blank=True, max_length=50)),
                ('nome_pai', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
