# Generated by Django 5.0.2 on 2024-07-31 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0004_paciente_id_alter_paciente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('nome_paciente', models.CharField(max_length=50)),
                ('nome_medico', models.CharField(max_length=50)),
                ('cpf_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
                ('cpf_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
