# Generated by Django 5.0.2 on 2024-07-31 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_cpf_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cpf_medico',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='cpf_paciente',
        ),
    ]
