# Generated by Django 5.0.2 on 2024-07-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rg', models.CharField(max_length=20)),
                ('num_cart_trab', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True)),
                ('rua', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(blank=True, max_length=5)),
                ('complemento', models.TextField(blank=True)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('ponto_referencia', models.TextField(blank=True)),
                ('data_admissao', models.DateField(blank=True)),
            ],
        ),
    ]
