# Generated by Django 5.0.2 on 2024-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_alter_funcionario_bairro_alter_funcionario_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
