# Generated by Django 5.0.2 on 2024-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_funcionario_id_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
