# Generated by Django 5.0.2 on 2024-07-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
