# Generated by Django 5.0.2 on 2024-07-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(null=True, verbose_name='Data da Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='num_cart_trab',
            field=models.CharField(max_length=20, verbose_name='Numero Carteira de Trabalho'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ponto_referencia',
            field=models.TextField(blank=True, verbose_name='Ponto de referência'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rua',
            field=models.CharField(max_length=50),
        ),
    ]
