# Generated by Django 5.0.2 on 2024-07-31 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0004_paciente_id_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cpf_medico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cpf_paciente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medico'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
